# -*- coding: utf-8 -*-
"""DecisionTree_Assigememt_patrikaki.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17w9j1I5CH8LdwK0AW0AxtEtPzII4PJ8U

# **Decision Tree Analysis for Heart Disease Predictions**

1. Introduction to decision trees

---

***-> What's a Decision Tree?***


>A Decision Tree is a machine learning algorithm which uses labelled input and output datasets to train models. The approach is used mainly to solve classification and regression problems.
It is called a "tree" because of its hierarchical structure.
Tree consists of internal nodes representing tests on features (attributes), branches that represent the outcomes of these tests, and leaf nodes that represent class labels or regression values.
The topmost node is called the root node, and it serves as the starting point for decision-making. The tree splits data into subsets based on the values of input features until the final decision.



***-> How does it work?***


>A decision tree works by learning simple decision rules from labeled input data to predict an outcome. It begins at the root node, which represents the initial question or condition related to a particular feature. Based on the answer to this question (true or false), the data is split into different branches, each leading to an internal node. These nodes continue asking further questions, refining the data with each step. This process of splitting continues until a stopping condition is met, such as a maximum tree depth, a minimum number of samples in a node, or all samples in a node belonging to the same class. At every level, the tree evaluates the feature that best separates the data to increase prediction accuracy. The result is a model that can be easily interpreted and visualized, making Decision Trees particularly useful in domains where explainability is important.

2. Data Preparation & Splitting

---
"""

#Importing all the necessary libraries.

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, classification_report
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

from sklearn import tree
from matplotlib import pyplot as plt
import seaborn as sns

#Importing the Heart Disease dataset from a URL and loading it into a dataframe

url = "https://raw.githubusercontent.com/sharmaroshan/Heart-UCI-Dataset/master/heart.csv"
dataframe = pd.read_csv(url, encoding='utf-8')  #heart disease dataset with 14 features
dataframe

"""Understand dataset structure and content"""

#Displaying basic information about the dataset: number of rows and columns,
# feature names, and the data types of each column

print("Informations of Database:")
print("• Number of rows : ", dataframe.shape[0])    #rows=dataframe.shape[0]
print("• Number of columns : ", dataframe.shape[1])  #columns=dataframe.shape[1]
print("• Names and Types of features : \n", dataframe.dtypes)

print(dataframe.describe())   #generate a statistical summary of the dataset

"""Check for missing/null values in the dataset"""

#check for null values in each column

dataframe.isnull().sum()

#check if any null values exist in the whole dataset

dataframe.isnull().sum().sum()

"""Plotting histograms of the dataset features to observe the distribution of values.



"""

# Plotting histograms to visualize how the values are distributed across each numeric feature
# in the dataset before performing further analysis

dataframe.hist(figsize=(20,20))
plt.suptitle('Histograms of Features', fontsize=20)
plt.tight_layout()
plt.show()

"""The heatmap below visualizes how features are correlated with each other. Highly correlated variables may carry redundant information and can influence model performance.

"""

# Plotting a correlation heatmap to visualize the relationships
#between numeric features in the dataset

fig = plt.figure(figsize=(20,20))
plt.title("Correlation Heatmap")
_=sns.heatmap(dataframe.corr(),  annot=True)
plt.tight_layout()
plt.show()

# Plotting boxplot to visualize the distribution, spread,
#skewness, and outliers in dataframe.

fig=plt.figure(figsize=(10,10))
_=sns.boxplot(dataframe)
plt.title('Box Plot of Features')
plt.tight_layout()
plt.show()

"""**Train-test split** is a technique used to divide a dataset into two parts: a training set and a testing set. The training set is used to teach the model, allowing it to learn patterns from the data. The testing set, on the other hand, is kept separate and is used to evaluate the model's performance on unseen data. This helps in assessing how well the model generalizes to new inputs and prevents overfitting."""

#Train the model

# Define features (X) and target (y)
X = dataframe.drop(['target'], axis=1)
y=dataframe['target']

# Split the data into training and testing sets (67% train, 33% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

"""Parameters of train_test_split() function:

* X: features (input variables)

* y: target (label to predict)

* test_size=0.33: defines the proportion of the dataset to include in the test split. 0.33 means 33% of the data will be used for testing, and the rest (67%) for training

* random_state=42: controls the random number generator used when splitting the data. It ensures that the train-test split gets the same split every time you run the code.

3. Model Training & Visualization


---
"""

# Try depth 4
clf_4 = DecisionTreeClassifier(max_depth=4, random_state=42)
clf_4.fit(X_train, y_train)
pred_4 = clf_4.predict(X_test)

# Try depth 5
clf_5 = DecisionTreeClassifier(max_depth=5, random_state=42)
clf_5.fit(X_train, y_train)
pred_5 = clf_5.predict(X_test)

print("Accuracy max_depth=4 :", accuracy_score(y_test, pred_4))
print("Accuracy max_depth=5 :", accuracy_score(y_test, pred_5))

"""There’s only a 2% increase in accuracy when increasing the depth, so setting the max depth to 4 is a better choice for healthcare. It keeps the model easier to understand and visualize. Even if a deeper tree slightly improves accuracy, it’s not worth the extra complexity, especially when explainability is important (clear decisions matter most)."""

#Initialize and train a Decision Tree model on the dataset

clf = DecisionTreeClassifier(max_depth=4, ccp_alpha=0.01) #initialize
clf.fit(X_train, y_train) #train

clf.get_depth()

#view hyperparameters

clf.get_params()

"""**Explain hyperparameters:**

`'ccp_alpha': 0.01`

Complexity parameter used for Minimal Cost-Complexity Pruning. The subtree with the largest cost complexity that is smaller than ccp_alpha will be chosen. 0.01 means small subtrees that don’t improve performance much will be removed to ovoid overfitting.

` 'class_weight': None`

Weights associated with classes in the form {class_label: weight}. If None, all classes are supposed to have weight one.


` 'criterion': 'gini'`

The function to measure the quality of a split. Supported criteria are “gini” for the Gini impurity.

` 'max_depth': 4`

The maximum depth of the tree is equal to 4.

` 'max_features': None`

The number of features to consider when looking for the best split.If None, then max_features=n_features.

` 'max_leaf_nodes': None`

Best nodes are defined as relative reduction in impurity. If None then unlimited number of leaf nodes.

` 'min_impurity_decrease': 0.0`

A node will be split if this split induces a decrease of the impurity greater than or equal to this value.

` 'min_samples_leaf': 1`

The minimum number of samples required to be at a leaf node.

` 'min_samples_split': 2`

he minimum number of samples required to split an internal node.

` 'min_weight_fraction_leaf': 0.0`

The minimum weighted fraction of the sum total of weights (of all the input samples) required to be at a leaf node. Samples have equal weight when sample_weight is not provided.

` 'monotonic_cst': None`

Indicates the monotonicity constraint to enforce on each feature.If monotonic_cst is None, no constraints are applied.

` 'random_state': None`

Controls the randomness of the estimator.

` 'splitter': 'best'`

The strategy used to choose the split at each node. Supported strategies are “best” to choose the best split and “random” to choose the best random split.



"""

clf.classes_

"""The plot below represents the trained decision tree. Each node shows the feature used for splitting, the Gini index, and the class prediction."""

# Visualizing the trained decision tree

fig = plt.figure(figsize=(25,20))
_ = tree.plot_tree(
    clf,
    feature_names=X.columns,
    class_names=['No Disease', 'Heart Disease'],
    filled=True,
    fontsize=12
)
plt.title("Decision Tree Visualization", fontsize=20)
plt.show()

"""* Each internal node: test one attribute X or the value of feature against a threshold
* Each branch from a node: selects one value for X
* Each leaf node: predict Y (p(Y|x ∈ leaf)

The decision tree graph shows how the model splits data based on different features to classify tumors as Malignant or Benign (0 => No Desease, 1 => Heart Desease). Each node represents a decision based on a feature threshold, and the tree branches until it reaches a final prediction. The color (orange for No Desease, blue for Heart Desease) and label of each node show the predicted class and how confident the model is at that point.
The deeper the color, the more confident the prediction.
The top of the tree (where the model starts splitting) holds the most important decisions, and as you move down, the decisions become more specific.

4. Model Evaluation

---
"""

#Predict on test data

predictions = clf.predict(X_test)
predictions

clf.predict_proba(X_test) #probabilities for each class

#calculate accuracy

#The accuracy score gives us the percentage of correct predictions.

print("Accuracy:", accuracy_score(y_test, predictions))

#calculate precision

#The precision score gives us the percentage of positive predictions
#that were actually correct.
#Precision is about the quality of the positive predictions.

print("Precision:",precision_score(y_test, predictions))

#calculate recall

#The recall score gives us the percentage of actual positive
#instances that were correctly predicted by the model.
#Recall is about how many of the true positives were captured.

print("Recall:",recall_score(y_test, predictions))

#evaluate the classifier’s performance

report = classification_report(y_test, predictions, target_names=['No Disease', 'Heart Disease'])
print(report)

#Confusion Matrix

cm = confusion_matrix(y_test, predictions, labels=[0,1])
cm

#Display the Confusion Matrix
dispCm = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['No Disease', 'Heart Disease'])
dispCm.plot()
plt.title("Confusion Matrix")
plt.show()

#another way to visualize the confusion matrix by using heatmap
sns.heatmap(cm, annot=True)
plt.title("Confusion Matrix")
plt.show()

"""-->   In the confusion matrix, the top left cell (35) shows the number of 'no desease' cases that were correctly predicted as 'no desese' (true positives).


-->The top right cell (7) shows the number of 'no desease' cases that were incorrectly predicted as 'heart desease' (false negatives).


-->The bottom left cell (14) shows the number of 'heart desease' cases that were incorrectly predicted as 'no desease' (false positives).


-->The bottom right cell (44) shows the number of 'heart desease' cases that were correctly predicted as 'heart desease' (true negatives).

5. Final Analysis & Conclusion


---
"""

print(clf.feature_importances_)

feature_names=X.columns
feature_importance = pd.DataFrame(clf.feature_importances_, index = feature_names).sort_values(0, ascending=False)
feature_importance

features = list(feature_importance[feature_importance[0]>0].index)
print('The most import features are:\n', features)

feature_importance.head(10).plot(kind='bar')
plt.title("Feature Importance")
plt.show()

"""The original dataset contains 14 columns, including the target variable, meaning a total of 13 features were initially considered for model training. However, based on analysis, only 7 features appear to be relevant for visualization and potentially for building a better-performing model. Therefore, removing the remaining features could help reduce noise and improve model efficiency."""

low_importance = list(feature_importance[feature_importance[0]<0.07].index)

# Drop low importance features from the first dataframe X
X_reduced = X.drop(columns=low_importance)

X_reduced

#Displaying the new dataframe imformations
#without the unnecessary features

print("The database has:")
print("• Number of rows : ", X_reduced.shape[0])
print("• Number of columns : ", X_reduced.shape[1])
print("• Names and Types of features : \n", X_reduced.dtypes)

print(X_reduced.describe())

#train new model

X_train_new, X_test_new, y_train_new, y_test_new = train_test_split(X_reduced, y, test_size=0.33, random_state=42)

#Train new Decision Tree model

clf_new = DecisionTreeClassifier(max_depth=4, ccp_alpha=0.01)
clf_new.fit(X_train_new, y_train_new)

#display the decision tree graph

fig = plt.figure(figsize=(20,15))
_ = tree.plot_tree(
    clf_new,
    feature_names=X_reduced.columns,
    class_names=['No Disease', 'Heart Disease'],
    filled=True,
    fontsize=12
)
plt.title("DECISION TREE GRAPH (NEW)")
plt.show()

predictions_new = clf_new.predict(X_test_new)
predictions_new

#calculate accuracy

print("Accuracy:", accuracy_score(y_test_new, predictions_new))

print("Precision:",precision_score(y_test_new, predictions_new))

print("Recall:",recall_score(y_test_new, predictions_new))

#evaluate the classifier’s performance

report_new = classification_report(y_test_new, predictions_new, target_names=['No Disease', 'Heart Disease'])
print(report_new)

cm_new = confusion_matrix(y_test_new, predictions_new, labels=[0,1])
cm_new

print(clf_new.feature_importances_)

"""# **Final thoughts on the model's performance**


To predict the target variable, the model initially considered 13 features. However, after training the model and analyzing feature importance scores, it became evident that not all features contributed equally to the predictions.

Among the evaluated features, ca demonstrated the highest importance, followed closely by thal and cp. These variables significantly influenced the decision-making process of the model and were retained. On the other hand, features such as sex, trestbps, and chol showed zero importance scores, indicating they had no impact on the model’s outcomes.

To optimize performance, feature with importance under 0.07 were removed from the dataset. This decision was based on their lack of contribution to predictive accuracy and the potential drawbacks of including irrelevant variables, such as increased complexity and overfitting.

After removing features with low importance scores, the classification model retained its accuracy at 79%, demonstrating that excluding irrelevant variables did not hinder its predictive performance. While there were minor trade-offs between precision and recall for the two classes (No Disease and Heart Disease), the overall balance of metrics remained consistent. For the No Disease class, precision improved slightly, while recall dropped. Conversely, for the Heart Disease class, recall improved but precision decreased modestly.

These adjustments indicate that simplifying the feature set resulted in negligible impact on model performance, supporting the decision to streamline the dataset for better interpretability and reduced complexity. By focusing on the most influential features, the model is optimized to generalize effectively to new data and is better equipped for practical use. Overall, the revised feature set enhances both the efficiency and reliability of the predictive system.

"""