# -*- coding: utf-8 -*-
"""KNN_patrikaki.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L4gvdCmSdbPOXrKVEDqGL94fuhvESnFS

# Stroke Prediction: Decision Tree & KNN Models

# 1. Data Preparation

---
"""

#Importing all the necessary libraries.

import pandas as pd
import numpy as np
import kagglehub
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, classification_report
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import KFold

from sklearn import tree
from matplotlib import pyplot as plt
import seaborn as sns

"""#Load Dataset


"""

# Upload the stroke prediction dataset file from local machine

from google.colab import files
uploaded = files.upload()

# Download the stroke prediction dataset from Kaggle using kagglehub

path = kagglehub.dataset_download("fedesoriano/stroke-prediction-dataset")

csv_path = f"{path}/healthcare-dataset-stroke-data.csv"

df = pd.read_csv(csv_path)

print("Column headers:", df.columns.tolist())

"""# 2. Decision Tree Model


---

# STEP 1: Understand the dataframe
"""

#Displaying basic information about the dataset: number of rows and columns,
# feature names, and the data types of each column

print("Informations of Database:")
print("• Number of rows : ", df.shape[0])    #rows=dataframe.shape[0]
print("• Number of columns : ", df.shape[1])  #columns=dataframe.shape[1]
print("• Names and Types of features : \n", df.dtypes)

df.head()

print(df.info())

df.describe()

"""# STEP 2: Preprocess the data

#Handle Missing Values
"""

df.drop("id", axis=1, inplace=True)

# Display missing values
print("Missing values before handling:")
print(df.isnull().sum())

# Imputation (Filling In Missing Values)
df['bmi'] = df['bmi'].fillna(df['bmi'].mean())

# Check if there are still missing values
print("\nMissing values after handling:")
print(df.isnull().sum())

"""# Encoding categorical variables into numeric format for model training"""

print(df['gender'].value_counts())
print("\n")
print(df['ever_married'].value_counts())
print("\n")
print(df['work_type'].value_counts())
print("\n")
print(df['Residence_type'].value_counts())
print("\n")
print(df['smoking_status'].value_counts())

df['gender'] = df['gender'].map({'Male': 0, 'Female': 1, 'Other': 2})

df['ever_married'] = df['ever_married'].map({'No': 0, 'Yes': 1})

df['work_type'] = df['work_type'].map({'Private': 0,
                                        'Self-employed': 1,
                                       'children': 2,
                                       'Govt_job': 3,
                                       'Never_worked': 4})

df['Residence_type'] = df['Residence_type'].map({'Urban': 0, 'Rural': 1})

df['smoking_status'] = df['smoking_status'].map({'never smoked': 0,
                                                'formerly smoked': 1,
                                                'smokes': 2,
                                                 'Unknown': -1})

"""# Using one-hot encoding as an alternative"""

# One-hot encoding for categorical variables
df = pd.get_dummies(df, drop_first=True)
df.head()

"""# Confirm the updatted types of data"""

df.dtypes

df.head()

"""# Perform exploratory data analysis (EDA) using graphs"""

# Plotting histograms to visualize how the values are distributed across each numeric feature
# in the dataset before performing further analysis

df.hist(figsize=(10,10))
plt.suptitle('Histograms of Features', fontsize=20)
plt.tight_layout()
plt.show()

# Plotting a correlation heatmap to visualize the relationships
#between numeric features in the dataset

fig = plt.figure(figsize=(10,10))
plt.title("Correlation Heatmap")
_=sns.heatmap(df.corr(),  annot=True)
plt.tight_layout()
plt.show()

# Plotting boxplot to visualize the distribution, spread,
#skewness, and outliers in dataframe.

fig=plt.figure(figsize=(10,10))
_=sns.boxplot(df)
plt.title('Box Plot of Features')
plt.tight_layout()
plt.show()

"""# STEP 3: Train and Evaluate a Decision Tree Classifier

# Split Features and Data
"""

#Train the model

# Define features (X) and stroke (y)
X = df.drop(['stroke'], axis=1)
y=df['stroke']

# Split the data into training and testing sets (72% train, 28% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.28, random_state=42)

#Initialize and train a Decision Tree model on the dataset

dt = DecisionTreeClassifier() #initialize
dt.fit(X_train, y_train) #train

# Predictions and evaluation
y_pred_dt = dt.predict(X_test)
print("Decision Tree Classification Report:\n")
print(classification_report(y_test, y_pred_dt))

"""# Evaluate Model"""

#Predict on test data

predictions = dt.predict(X_test)
predictions

dt.predict_proba(X_test) #probabilities for each class

"""# Using accuracy, precision, recall, f1 score for evaluating the model"""

print("Accuracy:", accuracy_score(y_test, predictions))
print("Precision:",precision_score(y_test, predictions))
print("Recall:",recall_score(y_test, predictions))
print("F1 Score:",f1_score(y_test, predictions))

#evaluate the classifier’s performance

report = classification_report(y_test, predictions, target_names=['No Stroke', 'Stroke'])
print(report)

"""# Select only the Most Important Features for Improved Model Performance"""

feature_names=X.columns
feature_importance = pd.DataFrame(dt.feature_importances_, index = feature_names).sort_values(0, ascending=False)
feature_importance

features = list(feature_importance[feature_importance[0]>0].index)
print('The most import features are:\n', features)

feature_importance.head(10).plot(kind='bar')
plt.title("Feature Importance")
plt.show()

low_importance = list(feature_importance[feature_importance[0]<0.03].index)

# Drop low importance features from the first dataframe X
# Removal (Drop Missing Data)
df = df.drop(columns=low_importance)
df.head()

df.head()

"""#Fine-tune the Decision Tree Model"""

# Define parameter grid
param_grid = {
    'max_depth': [3, 5, 10, 15, 17],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Initialize GridSearchCV
grid_search = GridSearchCV(DecisionTreeClassifier(random_state=42), param_grid, cv=5, scoring='f1')
grid_search.fit(X_train, y_train)

# Best parameters and score
print("Best Parameters:", grid_search.best_params_)
print("Best F1 Score (CV):", grid_search.best_score_)

# Evaluate best estimator on test set
best_dt_model = grid_search.best_estimator_
y_pred_best_dt = best_dt_model.predict(X_test)
print("Fine-tuned Decision Tree Classification Report:\n")
print(classification_report(y_test, y_pred_best_dt))

"""# Interpret the Model"""

# Visualizing the trained decision tree
plt.figure(figsize=(20,10))
tree.plot_tree(
    best_dt_model,
    feature_names=X.columns,
    class_names=['No Stroke', 'Stroke'],
    filled=True
)
plt.title("Decision Tree Visualization", fontsize=20)
plt.show()

"""# 3. KNN Model

---

# Data Processing
"""

df = pd.read_csv(csv_path)

print("Column headers:", df.columns.tolist())

selected_features = ['age', 'work_type', 'bmi', 'avg_glucose_level', 'smoking_status', 'stroke']
df = df[selected_features]

# Display missing values
print("Missing values before handling:")
print(df.isnull().sum())

# Imputation (Filling In Missing Values)
df['bmi'] = df['bmi'].fillna(df['bmi'].mean())

# Display missing values
print("\nMissing values after handling:")
print(df.isnull().sum())

df['work_type'] = df['work_type'].map({'Private': 0,
                                        'Self-employed': 1,
                                       'children': 2,
                                       'Govt_job': 3,
                                       'Never_worked': 4})

df['smoking_status'] = df['smoking_status'].map({'never smoked': 0,
                                                'formerly smoked': 1,
                                                'smokes': 2,
                                                 'Unknown': -1})

# Define features (X) and stroke (y)
X_knn = df.drop(['stroke'], axis=1)
y=df['stroke']

"""# Feature Scaling"""

scaler = StandardScaler()
X_knn_scaled = scaler.fit_transform(X_knn)

"""# Spil the data"""

# Train-test split (80/20)
X_train_knn, X_test_knn, y_train_knn, y_test_knn = train_test_split(X_knn_scaled, y,
                                                                    test_size=0.20,
                                                                    random_state=42)

"""# Build the KNN Model"""

# define the parameters we are gonna iterate through

n_neighbors = list(range(1,15))

test_accuracy = {}
train_accuracy = {}

for n in n_neighbors:
    clf = KNeighborsClassifier(n_neighbors = n)
    clf.fit(X_train, y_train)
    test_acc = clf.score(X_test, y_test)
    train_acc = clf.score(X_train, y_train)
    test_accuracy[n] = test_acc
    train_accuracy[n] = train_acc

for k, v in test_accuracy.items():
    print("test accuracy for {} n_neighbors is {} %".format(k, round(v*100, 3)))

for k, v in train_accuracy.items():
    print("training accuracy for {} n_neighbors is {} %".format(k, round(v*100, 3)))

# Create lists for plotting
test_acc_values = [test_accuracy[n] for n in n_neighbors]
train_acc_values = [train_accuracy[n] for n in n_neighbors]

# Plotting
plt.figure(figsize=(10, 6))
plt.plot(n_neighbors, train_acc_values, label='Training Accuracy')
plt.plot(n_neighbors, test_acc_values, label='Test Accuracy')
plt.title('KNN Accuracy vs Number of Neighbors')
plt.xlabel('Number of Neighbors (k)')
plt.ylabel('Accuracy (%)')
plt.xticks(n_neighbors)
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

"""Based on the diagram and the accuracy values, the best choice for n_neighbors is 8, as it delivers the highest test accuracy (93.99%) and a very good training accuracy (95.57%). That is also means that the model achieves a strong balance between learning the training data.



"""

knn = KNeighborsClassifier(n_neighbors=8)
knn.fit(X_train_knn, y_train_knn)

knn.get_params()

"""# Evaluate the Model

"""

#evaluate the model's accuracy
training_acc=knn.score(X_train_knn, y_train_knn)
test_acc=knn.score(X_test_knn, y_test_knn)

training_acc, test_acc

#Predict on test data

predictions_knn = knn.predict(X_test_knn)
predictions_knn

knn.predict_proba(X_test_knn) #probabilities for each class

print("Accuracy:", accuracy_score(y_test_knn, predictions_knn))
print("Precision:",precision_score(y_test_knn, predictions_knn))
print("Recall:",recall_score(y_test_knn, predictions_knn))
print("F1 Score:",f1_score(y_test_knn, predictions_knn))

report = classification_report(y_test_knn, predictions_knn, target_names=['No Stroke', 'Stroke'])
print(report)

"""Although the KNN model with k=8 shows a high accuracy of 93.93%, the precision, recall, and F1 score are all 0.0. This happens because the model predicts only the majority class and completely misses the minority class. As a result, it fails to identify any true positive cases. This is a common issue when the dataset is imbalanced, because we have a huge number of zeros and a small number of 1s. This means that accuracy alone is not enough to judge the model's performance, especially when correct classification (1 for stroke) of all classes is important.

# Fine-Tune the KNN Model
"""

# Define the hyperparameter distribution
param_dist_knn = {
    'n_neighbors': range(1, 10),  # Try K from 1 to 9
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan']
}

# Random search with 5-fold cross-validation using F1 score
random_search_knn = RandomizedSearchCV(
    estimator=KNeighborsClassifier(),
    param_distributions=param_dist_knn,
    n_iter=20,              # Try 20 random combinations
    scoring='f1',           # F1 score (focuses on positive class)
    cv=5,
    n_jobs=-1,
    random_state=42
)

# Fit the model to the training data
random_search_knn.fit(X_train_knn, y_train_knn)

# Best parameters and F1 score
print("Best Parameters (Random Search):", random_search_knn.best_params_)
print("Best F1 Score:", random_search_knn.best_score_)

# Evaluate the best model on the test set
best_knn_model = random_search_knn.best_estimator_
y_pred_best_knn = best_knn_model.predict(X_test_knn)

print("\nFine-tuned KNN Classification Report:\n")
print(classification_report(y_test_knn, y_pred_best_knn))

best_knn_model.get_params()

"""# Confusion matrixes to compare results for decision tree and KNN"""

#Confusion Matrix

cm = confusion_matrix(y_test, predictions, labels=[0,1])
cm_knn = confusion_matrix(y_test_knn, predictions_knn, labels=[0,1])
cm_knn_best = confusion_matrix(y_test_knn, best_knn_model.predict(X_test_knn), labels=[0,1])

#Display the Confusion Matrix (Decision Tree)
dispCm = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['No Stroke', 'Stroke'])
dispCm.plot()
plt.title("Confusion Matrix (Decision Tree)")
plt.show()

#Display the Confusion Matrix (KNN)
dispCm_knn = ConfusionMatrixDisplay(confusion_matrix=cm_knn, display_labels=['No Stroke', 'Stroke'])
dispCm_knn.plot()
plt.title("Confusion Matrix (KNN)")
plt.show()

#Display the Confusion Matrix (KNN best model)
dispCm_knn_best = ConfusionMatrixDisplay(confusion_matrix=cm_knn_best, display_labels=['No Stroke', 'Stroke'])
dispCm_knn_best.plot()
plt.title("Confusion Matrix (KNN best model)")
plt.show()

"""In comparing the KNN model and the Decision Tree model using their confusion matrices, both models achieved similar overall accuracy (Decision Tree = 91% & KNN =94%) . However, when focusing on stroke prediction — which is the minority but most critical class — the Decision Tree clearly outperformed KNN.

The Decision Tree model achieved a recall of 19.8% and a precision of 23.6% for detecting stroke cases, while the KNN model had a much lower recall of only 14% and precision of 11%. This means that the Decision Tree was more effective both in identifying actual stroke cases and in making correct positive predictions.

Although both models had a high number of false negatives (missed stroke cases), KNN performed significantly worse in this regard, identifying only 7 stroke cases correctly out of 62. In contrast, the Decision Tree correctly identified 19 out of 86 stroke cases.
"""